### ISSUE TITLE
Shouldn't root_url be site.url?

### ISSUE THREAD

**Issue by fjcaetano** [jez/hpstr-theme#15]
In a lot of places, there's reference to a `root_url` variable, but it's undefinable. Shouldn't it be `site.url`?

This is breaking stuff like sharing.

**Comment by jez** [comment]
This property is documented [here][1]. I use it throughout to solve many weird issues related to trailing slashes in various places.

[1]: https://github.com/jez/hpstr-theme/blob/1a3c137c3c2b459af20c3e3f6a00478fab756bc0/Properties.md#octopress-standard-properties

**Comment by fjcaetano** [comment]
I see. I assumed `site_root` may have been wrong because I only checked the sharing issue. But perhaps, the constructed url used in the sharing services should be `site.url`.

Facebook sharing is not broken because I believe they may use the HTTP referer, but Twitter and G+ are. You can check it in your own [post footer](https://blog.jez.io/2015/06/12/show-where-a-python-package-is-used)

**Comment by jez** [comment]
Oh, I see. Thanks for reporting this. I've swapped it out with the `canonical` url that gets populated in `source/_includes/head.html`.

It should work now.

**Comment by fjcaetano** [comment]
It worked. Thanks!

Btw, I also did some changes to adapt to my needs and I think you may be interested in some of them. Is it cool if I submit some PRs for you consideration?

**Comment by jez** [comment]
Sure. If you have made a lot of changes, try to submit one PR for each distinct feature.

**Comment by fjcaetano** [comment]
Don't worry. I'll probably separate them on their own feature-branch and submit a PR for each so you can decide what works best.
