### ISSUE TITLE
Post featured image

### ISSUE THREAD

**Issue by fjcaetano** [jez/hpstr-theme#19]
Is there a reason why featured images for each post are not in the index? Would it be interesting?

I got it working on my fork: [Live Version](http://blog.flaviocaetano.com/)

**Comment by jez** [comment]
Nice!

I think it's mostly just because I tend to use the same image for most posts, and they're almost always not related to the content of the post.

**Comment by fjcaetano** [comment]
Hold on, don't close this issue yet! I'll submit the pull-request to "fix" this.

**Comment by jez** [comment]
Ok, sure. As long as it's opt-in, not opt-out. There should be something like a flag: `in_index: true` that defaults to `false`.

**Comment by fjcaetano** [comment]
The way I made it, if the user sets a feature image for a post, it will appear in the index. That means that if he doesn't set the image per post, it won't have any. 

Is that what you want to change, to make the user set a feature image per post AND add that `in_index` option?

**Comment by jez** [comment]
Yeah, for example, I have lots of feature images, on my blog, but I don't want any of them to show up in my index. I want it to be a feature that is there only if users enable it.

Also feel free to change `is_index` to something that makes more sense if you want.

**Comment by fjcaetano** [comment]
Ok, sure. All do that

**Comment by jez** [comment]
Also please add a section to this doc documenting how it works:

https://github.com/jez/hpstr-theme/blob/master/Properties.md#per-page-properties-page

**Comment by jez** [comment]
Now that I think about it, you might also want to add and check a `site.xyz` property that lets you configure it on a site-wide level, so that it's easy for people who disagree with my tastes and want it default-on. Something like

```ruby
if (page.is_index == true) || (page.is_index != false && site.is_index == true)
```

which would let you enable or disable it for the entire site, override that preference on a page-by-page basis, and fall back to no image if neither setting had been explicitly set to `true`.
