### ISSUE TITLE
Header Image and tab description

### ISSUE THREAD

**Issue by lsaravia** [jez/hpstr-theme#20]
Hi,

I am not an expert doing this  mostly I modified things by try and error, so I would like to change the header image randomly each time you load the blog, I will appreciate any advice in how to do this.

**Comment by jez** [comment]
This is not currently supported. If you wanted to implement it yourself, you'd have to write some JavaScript that was loaded on the home page that randomly selected the image you wanted.

**Comment by jasoncheng911** [comment]
Front page head picture I have already modified became my own pictures, but I click the page classification into the head picture I don't know where is the replacement.I described to understand?
